package main

import (
	"os"
	"regexp"
	"text/template"

	"github.com/typisttech/composer-semver-cli/internal"
)

const fileTemplateRaw = `# Test the "{{ .Name }}" case
# This file is generated by "internal/parse/success/main.go"
# DO NOT EDIT THIS FILE.

exec composer-semver parse '{{ .Input }}'
stdout '{{ .Output }}'
! stderr .
`

var cases = []data{
	// Taken from https://github.com/composer/semver/blob/b52829022cb18210bb84e44e457bd4e890f8d2a7/tests/VersionParserTest.php#L292-L300
	{"ignore stability flag 1", "1.0@dev", "== 1.0.0.0"},
	{"ignore stability flag 2", ">=1.0@beta", ">= 1.0.0.0-beta"},
	{"ignore stability flag 3", "dev-load-varnish-only-when-used as ^2.0@dev", "== dev-load-varnish-only-when-used"},
	{"ignore stability flag 4", "dev-load-varnish-only-when-used@dev as ^2.0@dev", "== dev-load-varnish-only-when-used"},

	// Taken from https://github.com/composer/semver/blob/b52829022cb18210bb84e44e457bd4e890f8d2a7/tests/VersionParserTest.php#L302-L308
	{"ignores reference on dev version 1", "1.0.x-dev#abcd123", "== 1.0.9999999.9999999-dev"},
	{"ignores reference on dev version 2", "1.0.x-dev#trunk/@123", "== 1.0.9999999.9999999-dev"},

	// Taken from https://github.com/composer/semver/blob/b52829022cb18210bb84e44e457bd4e890f8d2a7/tests/VersionParserTest.php#L342-L377
	{"match any", "*", "*"},
	{"match any/v", "v*", ">= 0.0.0.0-dev"},
	{"match any/2", "*.*", ">= 0.0.0.0-dev"},
	{"match any/2v", "v*.*", ">= 0.0.0.0-dev"},
	{"match any/3", "*.x.*", ">= 0.0.0.0-dev"},
	{"match any/4", "x.X.x.*", ">= 0.0.0.0-dev"},
	{"not equal", "<>1.0.0", "!= 1.0.0.0"},
	{"not equal/2", "!=1.0.0", "!= 1.0.0.0"},
	{"greater than", ">1.0.0", "> 1.0.0.0"},
	{"lesser than", "<1.2.3.4", "< 1.2.3.4-dev"},
	{"less/eq than", "<=1.2.3", "<= 1.2.3.0"},
	{"great/eq than", ">=1.2.3", ">= 1.2.3.0-dev"},
	{"equals", "=1.2.3", "== 1.2.3.0"},
	{"double equals", "==1.2.3", "== 1.2.3.0"},
	{"no op means eq", "1.2.3", "== 1.2.3.0"},
	{"completes version", "=1.0", "== 1.0.0.0"},
	{"shorthand beta", "1.2.3b5", "== 1.2.3.0-beta5"},
	{"shorthand alpha", "1.2.3a1", "== 1.2.3.0-alpha1"},
	{"shorthand patch", "1.2.3p1234", "== 1.2.3.0-patch1234"},
	{"shorthand patch/2", "1.2.3pl1234", "== 1.2.3.0-patch1234"},
	{"accepts spaces", ">= 1.2.3", ">= 1.2.3.0-dev"},
	{"accepts spaces/2", "< 1.2.3", "< 1.2.3.0-dev"},
	{"accepts spaces/3", "> 1.2.3", "> 1.2.3.0"},
	{"accepts master", ">=dev-master", ">= dev-master"},
	{"accepts master/2", "dev-master", "== dev-master"},
	{"accepts arbitrary", "dev-feature-a", "== dev-feature-a"},
	{"regression #550", "dev-some-fix", "== dev-some-fix"},
	{"regression #935", "dev-CAPS", "== dev-CAPS"},
	{"ignores aliases", "dev-master as 1.0.0", "== dev-master"},
	{"lesser than override", "<1.2.3.4-stable", "< 1.2.3.4"},
	{"great/eq than override", ">=1.2.3.4-stable", ">= 1.2.3.4"},
}

var fileTemplate = template.Must(template.New("").Parse(fileTemplateRaw))

type data struct {
	name      string
	Input     string
	rawOutput string
}

func (d data) Name() string {
	return d.name
}

func (d data) Output() string {
	return "^" + regexp.QuoteMeta(d.rawOutput) + "$"
}

func (d data) Write(f *os.File) error {
	return fileTemplate.Execute(f, d)
}

func main() {
	err := internal.Generate("parse/success", cases...)
	if err != nil {
		panic(err)
	}
}
