package main

import (
	"fmt"
	"os"
	"regexp"
	"text/template"

	"github.com/typisttech/composer-semver-cli/internal"
)

const fileTemplateRaw = `# DO NOT EDIT THIS FILE
# This file is generated by "internal/parse/success/main.go"
# Test the "{{ .Name }}" case

exec composer-semver parse '{{ .Input }}'
stdout '{{ .Output }}'
! stderr .
`

var cases = []data{
	// Taken from https://github.com/composer/semver/blob/b52829022cb18210bb84e44e457bd4e890f8d2a7/tests/VersionParserTest.php#L292-L300
	{"ignore stability flag/1", "1.0@dev", "== 1.0.0.0"},
	{"ignore stability flag/2", ">=1.0@beta", ">= 1.0.0.0-beta"},
	{"ignore stability flag/3", "dev-load-varnish-only-when-used as ^2.0@dev", "== dev-load-varnish-only-when-used"},
	{"ignore stability flag/4", "dev-load-varnish-only-when-used@dev as ^2.0@dev", "== dev-load-varnish-only-when-used"},

	// Taken from https://github.com/composer/semver/blob/b52829022cb18210bb84e44e457bd4e890f8d2a7/tests/VersionParserTest.php#L302-L308
	{"ignores reference on dev version/1", "1.0.x-dev#abcd123", "== 1.0.9999999.9999999-dev"},
	{"ignores reference on dev version/2", "1.0.x-dev#trunk/@123", "== 1.0.9999999.9999999-dev"},

	// Taken from https://github.com/composer/semver/blob/b52829022cb18210bb84e44e457bd4e890f8d2a7/tests/VersionParserTest.php#L342-L377
	{"simple/match any", "*", "*"},
	{"simple/match any/v", "v*", ">= 0.0.0.0-dev"},
	{"simple/match any/2", "*.*", ">= 0.0.0.0-dev"},
	{"simple/match any/2v", "v*.*", ">= 0.0.0.0-dev"},
	{"simple/match any/3", "*.x.*", ">= 0.0.0.0-dev"},
	{"simple/match any/4", "x.X.x.*", ">= 0.0.0.0-dev"},
	{"simple/not equal", "<>1.0.0", "!= 1.0.0.0"},
	{"simple/not equal/2", "!=1.0.0", "!= 1.0.0.0"},
	{"simple/greater than", ">1.0.0", "> 1.0.0.0"},
	{"simple/lesser than", "<1.2.3.4", "< 1.2.3.4-dev"},
	{"simple/less/eq than", "<=1.2.3", "<= 1.2.3.0"},
	{"simple/great/eq than", ">=1.2.3", ">= 1.2.3.0-dev"},
	{"simple/equals", "=1.2.3", "== 1.2.3.0"},
	{"simple/double equals", "==1.2.3", "== 1.2.3.0"},
	{"simple/no op means eq", "1.2.3", "== 1.2.3.0"},
	{"simple/completes version", "=1.0", "== 1.0.0.0"},
	{"simple/shorthand beta", "1.2.3b5", "== 1.2.3.0-beta5"},
	{"simple/shorthand alpha", "1.2.3a1", "== 1.2.3.0-alpha1"},
	{"simple/shorthand patch", "1.2.3p1234", "== 1.2.3.0-patch1234"},
	{"simple/shorthand patch/2", "1.2.3pl1234", "== 1.2.3.0-patch1234"},
	{"simple/accepts spaces", ">= 1.2.3", ">= 1.2.3.0-dev"},
	{"simple/accepts spaces/2", "< 1.2.3", "< 1.2.3.0-dev"},
	{"simple/accepts spaces/3", "> 1.2.3", "> 1.2.3.0"},
	{"simple/accepts master", ">=dev-master", ">= dev-master"},
	{"simple/accepts master/2", "dev-master", "== dev-master"},
	{"simple/accepts arbitrary", "dev-feature-a", "== dev-feature-a"},
	{"simple/regression #550", "dev-some-fix", "== dev-some-fix"},
	{"simple/regression #935", "dev-CAPS", "== dev-CAPS"},
	{"simple/ignores aliases", "dev-master as 1.0.0", "== dev-master"},
	{"simple/lesser than override", "<1.2.3.4-stable", "< 1.2.3.4"},
	{"simple/great/eq than override", ">=1.2.3.4-stable", ">= 1.2.3.4"},

	// Taken from https://github.com/composer/semver/blob/b52829022cb18210bb84e44e457bd4e890f8d2a7/tests/VersionParserTest.php#L401-L419
	{"wildcard/1", "v2.*", "[>= 2.0.0.0-dev < 3.0.0.0-dev]"},
	{"wildcard/2", "2.*.*", "[>= 2.0.0.0-dev < 3.0.0.0-dev]"},
	{"wildcard/3", "20.*", "[>= 20.0.0.0-dev < 21.0.0.0-dev]"},
	{"wildcard/4", "20.*.*", "[>= 20.0.0.0-dev < 21.0.0.0-dev]"},
	{"wildcard/5", "2.0.*", "[>= 2.0.0.0-dev < 2.1.0.0-dev]"},
	{"wildcard/6", "2.x", "[>= 2.0.0.0-dev < 3.0.0.0-dev]"},
	{"wildcard/7", "2.x.x", "[>= 2.0.0.0-dev < 3.0.0.0-dev]"},
	{"wildcard/8", "2.2.x", "[>= 2.2.0.0-dev < 2.3.0.0-dev]"},
	{"wildcard/9", "2.10.X", "[>= 2.10.0.0-dev < 2.11.0.0-dev]"},
	{"wildcard/10", "2.1.3.*", "[>= 2.1.3.0-dev < 2.1.4.0-dev]"},
	{"wildcard/11", "0.*", "< 1.0.0.0-dev"},
	{"wildcard/12", "0.*.*", "< 1.0.0.0-dev"},
	{"wildcard/13", "0.x", "< 1.0.0.0-dev"},
	{"wildcard/14", "0.x.x", "< 1.0.0.0-dev"},

	// Taken from https://github.com/composer/semver/blob/b52829022cb18210bb84e44e457bd4e890f8d2a7/tests/VersionParserTest.php#L443-L466
	{"tilde/1", "~v1", "[>= 1.0.0.0-dev < 2.0.0.0-dev]"},
	{"tilde/2", "~1.0", "[>= 1.0.0.0-dev < 2.0.0.0-dev]"},
	{"tilde/3", "~1.0.0", "[>= 1.0.0.0-dev < 1.1.0.0-dev]"},
	{"tilde/4", "~1.2", "[>= 1.2.0.0-dev < 2.0.0.0-dev]"},
	{"tilde/5", "~1.2.3", "[>= 1.2.3.0-dev < 1.3.0.0-dev]"},
	{"tilde/6", "~1.2.3.4", "[>= 1.2.3.4-dev < 1.2.4.0-dev]"},
	{"tilde/7", "~1.2-beta", "[>= 1.2.0.0-beta < 2.0.0.0-dev]"},
	{"tilde/8", "~1.2-b2", "[>= 1.2.0.0-beta2 < 2.0.0.0-dev]"},
	{"tilde/9", "~1.2-BETA2", "[>= 1.2.0.0-beta2 < 2.0.0.0-dev]"},
	{"tilde/10", "~1.2.2-dev", "[>= 1.2.2.0-dev < 1.3.0.0-dev]"},
	{"tilde/11", "~1.2.2-stable", "[>= 1.2.2.0 < 1.3.0.0-dev]"},
	{"tilde/12", "~201903.0", "[>= 201903.0-dev < 201904.0.0.0-dev]"},
	{"tilde/13", "~201903.0-beta", "[>= 201903.0-beta < 201904.0.0.0-dev]"},
	{"tilde/14", "~201903.0-stable", "[>= 201903.0 < 201904.0.0.0-dev]"},
	{"tilde/15", "~201903.205830.1-stable", "[>= 201903.205830.1 < 201903.205831.0.0-dev]"},
	{"tilde/16", "~2.x-dev", "[>= 2.9999999.9999999.9999999-dev < 3.0.0.0-dev]"},
	{"tilde/17", "~2.0.x-dev", "[>= 2.0.9999999.9999999-dev < 2.1.0.0-dev]"},
	{"tilde/18", "~2.0.3.x-dev", "[>= 2.0.3.9999999-dev < 2.0.4.0-dev]"},
	{"tilde/19", "~0.x-dev", "[>= 0.9999999.9999999.9999999-dev < 1.0.0.0-dev]"},

	// Taken from https://github.com/composer/semver/blob/b52829022cb18210bb84e44e457bd4e890f8d2a7/tests/VersionParserTest.php#L490-L516
	{"caret/1", "^v1", "[>= 1.0.0.0-dev < 2.0.0.0-dev]"},
	{"caret/2", "^0", "[>= 0.0.0.0-dev < 1.0.0.0-dev]"},
	{"caret/3", "^0.0", "[>= 0.0.0.0-dev < 0.1.0.0-dev]"},
	{"caret/4", "^1.2", "[>= 1.2.0.0-dev < 2.0.0.0-dev]"},
	{"caret/5", "^1.2.3-beta.2", "[>= 1.2.3.0-beta2 < 2.0.0.0-dev]"},
	{"caret/6", "^1.2.3.4", "[>= 1.2.3.4-dev < 2.0.0.0-dev]"},
	{"caret/7", "^1.2.3", "[>= 1.2.3.0-dev < 2.0.0.0-dev]"},
	{"caret/8", "^0.2.3", "[>= 0.2.3.0-dev < 0.3.0.0-dev]"},
	{"caret/9", "^0.2", "[>= 0.2.0.0-dev < 0.3.0.0-dev]"},
	{"caret/10", "^0.2.0", "[>= 0.2.0.0-dev < 0.3.0.0-dev]"},
	{"caret/11", "^0.0.3", "[>= 0.0.3.0-dev < 0.0.4.0-dev]"},
	{"caret/12", "^0.0.3-alpha", "[>= 0.0.3.0-alpha < 0.0.4.0-dev]"},
	{"caret/13", "^0.0.3-dev", "[>= 0.0.3.0-dev < 0.0.4.0-dev]"},
	{"caret/14", "^0.0.3-stable", "[>= 0.0.3.0 < 0.0.4.0-dev]"},
	{"caret/15", "^201903.0", "[>= 201903.0-dev < 201904.0.0.0-dev]"},
	{"caret/16", "^201903.0-beta", "[>= 201903.0-beta < 201904.0.0.0-dev]"},
	{"caret/17", "^201903.205830.1-stable", "[>= 201903.205830.1 < 201904.0.0.0-dev]"},
	{"caret/18", "^2.x-dev", "[>= 2.9999999.9999999.9999999-dev < 3.0.0.0-dev]"},
	{"caret/19", "^2.0.*-dev", "[>= 2.0.9999999.9999999-dev < 3.0.0.0-dev]"},
	{"caret/20", "^2.0.x-dev", "[>= 2.0.9999999.9999999-dev < 3.0.0.0-dev]"},
	{"caret/21", "^2.0.3.x-dev", "[>= 2.0.3.9999999-dev < 3.0.0.0-dev]"},
	{"caret/22", "^0.x-dev", "[>= 0.9999999.9999999.9999999-dev < 1.0.0.0-dev]"},

	// Taken from https://github.com/composer/semver/blob/b52829022cb18210bb84e44e457bd4e890f8d2a7/tests/VersionParserTest.php#L540-L558
	{"hyphen/1", "v1 - v2", "[>= 1.0.0.0-dev < 3.0.0.0-dev]"},
	{"hyphen/2", "1.2.3 - 2.3.4.5", "[>= 1.2.3.0-dev <= 2.3.4.5]"},
	{"hyphen/3", "1.2-beta - 2.3", "[>= 1.2.0.0-beta < 2.4.0.0-dev]"},
	{"hyphen/4", "1.2-beta - 2.3-dev", "[>= 1.2.0.0-beta <= 2.3.0.0-dev]"},
	{"hyphen/5", "1.2-RC - 2.3.1", "[>= 1.2.0.0-RC <= 2.3.1.0]"},
	{"hyphen/6", "1.2.3-alpha - 2.3-RC", "[>= 1.2.3.0-alpha <= 2.3.0.0-RC]"},
	{"hyphen/7", "1 - 2.0", "[>= 1.0.0.0-dev < 2.1.0.0-dev]"},
	{"hyphen/8", "1 - 2.1", "[>= 1.0.0.0-dev < 2.2.0.0-dev]"},
	{"hyphen/9", "1.2 - 2.1.0", "[>= 1.2.0.0-dev <= 2.1.0.0]"},
	{"hyphen/10", "1.3 - 2.1.3", "[>= 1.3.0.0-dev <= 2.1.3.0]"},
	{"hyphen/11", "2.0.3.x-dev - 3.0.3.x-dev", "[>= 2.0.3.9999999-dev <= 3.0.3.9999999-dev]"},
	{"hyphen/12", "2.0.x-dev - 3.0.x-dev", "[>= 2.0.9999999.9999999-dev <= 3.0.9999999.9999999-dev]"},
	{"hyphen/13", "2.x-dev - 3.x-dev", "[>= 2.9999999.9999999.9999999-dev <= 3.9999999.9999999.9999999-dev]"},
	{"hyphen/14", "0.x-dev - 1.x-dev", "[>= 0.9999999.9999999.9999999-dev <= 1.9999999.9999999.9999999-dev]"},

	// Taken from https://github.com/composer/semver/blob/b52829022cb18210bb84e44e457bd4e890f8d2a7/tests/VersionParserTest.php#L575-L608
	{"numeric/1", "3.x-dev", "== 3.9999999.9999999.9999999-dev"},
	{"numeric/2", "3-dev", "== 3.0.0.0-dev"},
	{"non-numeric/1", "dev-3.x", "== dev-3.x"},
	{"non-numeric/2", "xsd2php-dev", "== dev-xsd2php"},
	{"non-numeric/3", "3.next-dev", "== dev-3.next"},
	{"non-numeric/4", "foobar-dev", "== dev-foobar"},
	{"non-numeric/5", "dev-xsd2php", "== dev-xsd2php"},
	{"non-numeric/6", "dev-3.next", "== dev-3.next"},
	{"non-numeric/7", "dev-foobar", "== dev-foobar"},
	{"non-numeric/8", "dev-1.0.0-dev<1.0.5-dev", "== dev-1.0.0-dev<1.0.5-dev"},
	{"non-numeric/9", "dev-1.0.0-dev<1.0.5", "== dev-1.0.0-dev<1.0.5"},
	{"non-numeric/10", "foobar-dev as 2.1.0", "== dev-foobar"},
	{"non-numeric/11", "foobar-dev as 2.1.0 || 3.5", "[== dev-foobar || == 3.5.0.0]"},
	{"non-numeric/12", "foobar-dev as 2.1.0 || 3.5 as 1.5", "[== dev-foobar || == 3.5.0.0]"},
	{"non-numeric/13", "2.1.0 - 2.3-dev", "[>= 2.1.0.0-dev <= 2.3.0.0-dev]"},
	{"non-numeric/14", "1.0 - 2.0.x-dev", "[>= 1.0.0.0-dev <= 2.0.9999999.9999999-dev]"},
	{"typo/1", "^1.", "[>= 1.0.0.0-dev < 2.0.0.0-dev]"},
	{"typo/2", "~1.", "[>= 1.0.0.0-dev < 2.0.0.0-dev]"},
	{"typo/3", "1.2.", "== 1.2.0.0"},
	{"typo/4", "1.2..dev", "== 1.2.0.0-dev"},
	{"typo/5", "1.2-.dev", "== 1.2.0.0-dev"},
	{"typo/6", "1.2_-dev", "== 1.2.0.0-dev"},
	{"complex", "~2.5.9|~2.6,>=2.6.2", "[[>= 2.5.9.0-dev < 2.6.0.0-dev] || [>= 2.6.0.0-dev < 3.0.0.0-dev >= 2.6.2.0-dev]]"},

	// Taken from https://github.com/composer/semver/blob/b52829022cb18210bb84e44e457bd4e890f8d2a7/tests/VersionParserTest.php#L627-L641
	{"multi/1/1", ">2.0,<=3.0", "[> 2.0.0.0 <= 3.0.0.0]"},
	{"multi/1/2", ">2.0 <=3.0", "[> 2.0.0.0 <= 3.0.0.0]"},
	{"multi/1/3", ">2.0  <=3.0", "[> 2.0.0.0 <= 3.0.0.0]"},
	{"multi/1/4", ">2.0, <=3.0", "[> 2.0.0.0 <= 3.0.0.0]"},
	{"multi/1/5", ">2.0 ,<=3.0", "[> 2.0.0.0 <= 3.0.0.0]"},
	{"multi/1/6", ">2.0 , <=3.0", "[> 2.0.0.0 <= 3.0.0.0]"},
	{"multi/1/7", ">2.0   , <=3.0", "[> 2.0.0.0 <= 3.0.0.0]"},
	{"multi/1/8", "> 2.0   <=  3.0", "[> 2.0.0.0 <= 3.0.0.0]"},
	{"multi/1/9", "> 2.0  ,  <=  3.0", "[> 2.0.0.0 <= 3.0.0.0]"},
	{"multi/1/10", "  > 2.0  ,  <=  3.0 ", "[> 2.0.0.0 <= 3.0.0.0]"},

	// Taken from https://github.com/composer/semver/blob/b52829022cb18210bb84e44e457bd4e890f8d2a7/tests/VersionParserTest.php#L643-L657
	{"multi with stability suffix/1", ">=1.1.0-alpha4,<1.2.x-dev", "[>= 1.1.0.0-alpha4 < 1.2.9999999.9999999-dev]"},
	{"multi with stability suffix/2", ">=1.1.0-alpha4,<1.2-beta2", "[>= 1.1.0.0-alpha4 < 1.2.0.0-beta2]"},

	// Taken from https://github.com/composer/semver/blob/b52829022cb18210bb84e44e457bd4e890f8d2a7/tests/VersionParserTest.php#L679-L686
	{"multi/2/1", ">2.0,<2.0.5 | >2.0.6", "[[> 2.0.0.0 < 2.0.5.0-dev] || > 2.0.6.0]"},
	{"multi/2/2", ">2.0,<2.0.5 || >2.0.6", "[[> 2.0.0.0 < 2.0.5.0-dev] || > 2.0.6.0]"},
	{"multi/2/3", "> 2.0 , <2.0.5 | >  2.0.6", "[[> 2.0.0.0 < 2.0.5.0-dev] || > 2.0.6.0]"},

	// Taken from https://github.com/composer/semver/blob/b52829022cb18210bb84e44e457bd4e890f8d2a7/tests/VersionParserTest.php#L688-L696
	{"multi with stabilities", ">2.0@stable,<=3.0@dev", "[> 2.0.0.0 <= 3.0.0.0-dev]"},

	// Taken from https://github.com/composer/semver/blob/b52829022cb18210bb84e44e457bd4e890f8d2a7/tests/VersionParserTest.php#L698-L706
	{"multi with stabilities wildcard", "2.0@stable,@dev", "[== 2.0.0.0 *]"},

	// Taken from https://github.com/composer/semver/blob/b52829022cb18210bb84e44e457bd4e890f8d2a7/tests/VersionParserTest.php#L708-L716
	{"multi with stabilities zero", ">2.0@stable || 0@dev", "[> 2.0.0.0 || == 0.0.0.0]"},
}

var fileTemplate = template.Must(template.New("").Parse(fileTemplateRaw))

type data struct {
	name      string
	Input     string
	rawOutput string
}

func (d data) Name() string {
	return d.name
}

func (d data) Output() string {
	q := regexp.QuoteMeta(d.rawOutput)
	return fmt.Sprintf(`^%s$`, q)
}

func (d data) Write(f *os.File) error {
	return fileTemplate.Execute(f, d)
}

func main() {
	err := internal.Generate("parse/success", cases...)
	if err != nil {
		panic(err)
	}
}
