package main

import (
	"fmt"
	"os"
	"regexp"
	"strings"
	"text/template"

	"github.com/typisttech/composer-semver-cli/internal"
)

const fileTemplateRaw = `# Test the "{{ .Name }}" case
# This file is generated by "internal/normalize/fail_and_report_aliasee_issue/main.go"
# DO NOT EDIT THIS FILE.

! exec composer-semver normalize --full-version='{{ .FullVersion }}' '{{ .AliasSource }}'
! stdout .
stderr '{{ .Output }}'
`

// Taken from https://github.com/composer/semver/blob/b52829022cb18210bb84e44e457bd4e890f8d2a7/tests/VersionParserTest.php#L247-L256
var cases = []data{
	{"Alias and caret", "^2.0 as 1.0.0+foo"},
	{"Alias and tilde", "~2.0 as  1.0.0+foo"},
	{"Alias and greater than", ">2.0  as 1.0.0+foo"},
	{"Alias and less than", "<2.0 as 1.0.0+foo"},
	{"Bad aliasee with stability", "<2.0@dev as 1.2.3@dev"},
}

var fileTemplate = template.Must(template.New("").Parse(fileTemplateRaw))

type data struct {
	name        string
	FullVersion string
}

func (d data) Name() string {
	return d.name
}

var re = regexp.MustCompile(`^([^,\s#]+)(?:#[^ ]+)? +as +([^,\s]+)$`)

func (d data) AliasSource() string {
	m := re.FindAllStringSubmatch(d.FullVersion, 1)
	if len(m) != 1 || len(m[0]) != 3 {
		panic("Bad full version(" + d.name + "): " + d.FullVersion)
	}

	return m[0][1]
}

func (d data) Alias() string {
	m := re.FindAllStringSubmatch(d.FullVersion, 1)
	if len(m) != 1 || len(m[0]) != 3 {
		panic("Bad full version(" + d.name + "): " + d.FullVersion)
	}

	return m[0][2]
}

const errMsg = `[ERROR] Invalid version string "%s" in "%s", the alias source must be an exact version, if ###EOL### it is a ###EOL### branch name you should prefix it with dev-`

func (d data) Output() string {
	s := fmt.Sprintf(errMsg, d.AliasSource(), d.FullVersion)
	q := regexp.QuoteMeta(s)
	q = strings.ReplaceAll(q, " ###EOL### ", `\s+`)
	return fmt.Sprintf(`^\s+%s\s+$`, q)
}

func (d data) Write(f *os.File) error {
	return fileTemplate.Execute(f, d)
}

func main() {
	err := internal.Generate("normalize/fail_and_report_aliasee_issue", cases...)
	if err != nil {
		panic(err)
	}
}
