name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: {}

jobs:
  phar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
          tools: box:4

      - uses: ramsey/composer-install@v3
        with:
          composer-options: --no-dev --prefer-dist

      - run: box compile

      - uses: actions/upload-artifact@v4
        with:
          name: composer-semver.phar
          path: phar/composer-semver
          if-no-files-found: error

  build:
    needs: phar
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-24.04-arm
          - ubuntu-24.04
          - macos-15
          - macos-15-intel

    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Set environment variables
        run: |
          OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
          ARCH="$(uname -m)"
          test "$ARCH" = "aarch64" && ARCH="arm64" || ARCH="amd64"

          echo "OS=$OS" >> $GITHUB_ENV
          echo "ARCH=$ARCH" >> $GITHUB_ENV

          test "$OS" = "darwin" && SPC_OS="macos" || SPC_OS="OS"
          test "$ARCH" = "arm64" && SPC_ARCH="aarch64" || SPC_ARCH="x86_64"

          echo "SPC_OS=$SPC_OS" >> $GITHUB_ENV
          echo "SPC_ARCH=$SPC_ARCH" >> $GITHUB_ENV

      - name: Download spc
        run: |
          gh release download --repo crazywhalecc/static-php-cli --pattern "spc-$SPC_OS-$SPC_ARCH.tar.gz" --output spc.tar.gz && \
          mkdir -p /tmp/spc && \
          tar -xzvf spc.tar.gz --directory /tmp/spc && \
          echo "/tmp/spc" >> "$GITHUB_PATH"
        env:
          GH_TOKEN: ${{ github.token }}

      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            craft.yml
          sparse-checkout-cone-mode: false
      - run: spc craft
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - uses: actions/download-artifact@v5
        with:
          name: composer-semver.phar
          path: phar
      - run: file "$WORKSPACE/phar/composer-semver"
        env:
          WORKSPACE: ${{ github.workspace }}
      - run: mkdir -p out
      - run: spc micro:combine phar/composer-semver --output out/composer-semver

      - uses: actions/upload-artifact@v4
        with:
          name: "composer-semver-${{ env.OS }}-${{ env.ARCH }}"
          path: out/composer-semver
          if-no-files-found: error

  test:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-24.04-arm
          - ubuntu-24.04
          - macos-15
          - macos-15-intel

    runs-on: ${{ matrix.runs-on }}
    env:
      GOFLAGS: '-mod=mod'
    steps:
      - name: Set environment variables
        run: |
          OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
          ARCH="$(uname -m)"
          test "$ARCH" = "aarch64" && ARCH="arm64" || ARCH="amd64"

          echo "OS=$OS" >> $GITHUB_ENV
          echo "ARCH=$ARCH" >> $GITHUB_ENV

      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v5
        with:
          name: "composer-semver-${{ env.OS }}-${{ env.ARCH }}"
          path: out

      - run: echo "$WORKSPACE/out" >> "$GITHUB_PATH"
        env:
          WORKSPACE: ${{ github.workspace }}
      - name: Print composer-semver binary path
        run: go test -count=1 -v ./internal

      - run: go test -count=1 ./...
