name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: {}

jobs:
  php-matrix:
    runs-on: ubuntu-latest
    outputs:
      highest: ${{ fromJSON(steps.php-matrix.outputs.matrix).highest }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            composer.json
          sparse-checkout-cone-mode: false
      - uses: typisttech/php-matrix-action@v1
        id: php-matrix

  phpstan:
    runs-on: ubuntu-latest
    needs: php-matrix
    steps:
      - uses: actions/checkout@v5

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ needs.php-matrix.outputs.highest }}
          coverage: none

      - uses: ramsey/composer-install@v3
        with:
          composer-options: --no-audit --optimize-autoloader
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.GITHUB_TOKEN }}"}}'

      - run: phpstan analyse

  box:
    runs-on: ubuntu-latest
    needs: php-matrix
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            box.json
          sparse-checkout-cone-mode: false

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ needs.php-matrix.outputs.highest }}
          coverage: none
          tools: box:4

      - run: box validate
