name: Publish

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions: {}

jobs:
  cloudsmith:
    runs-on: ubuntu-latest
    steps:
      - run: ${{ tojson(github) }}
        shell: cat {0}

      - run: gh release download --pattern '*.deb' "${TAG}"
        env:
          TAG: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ github.token }}

      # TODO:
      - run: ls -R .

      - name: Attestation verification
        run: |
          for ARCH in ${ARCHS}; do
            echo "::group::==> ${ARCH}"
            gh attestation verify --repo "${REPO}" "composer-semver_Linux_${ARCH}.deb"
            echo "::endgroup::"
          done
        env:
          REPO: ${{ github.repository }}
          ARCHS: "arm64 amd64"
