name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - '**'


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: {}

env:
  GOFLAGS: '-mod=mod'

jobs:
  phar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
          tools: box:4

      - uses: ramsey/composer-install@v3
        with:
          composer-options: --no-dev --prefer-dist

      - run: box compile

      - uses: actions/upload-artifact@v4
        with:
          name: composer-semver.phar
          path: phar/composer-semver
          if-no-files-found: error

  spc:
    needs: phar
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "linux"
            arch: "x86_64"
            runs-on: "ubuntu-latest"
          - os: "linux"
            arch: "aarch64"
            runs-on: "ubuntu-latest-arm"
          - os: "darwin"
            arch: "x86_64"
            runs-on: "macos-15-intel"
          - os: "darwin"
            arch: "aarch64"
            runs-on: "macos-latest"

    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Set architecture variables
        run: |
          if [[ "$OS" == "darwin" ]]; then
            echo "SPC=spc-macos-$ARCH.tar.gz" >> $GITHUB_ENV
          else
            echo "SPC=spc-$OS-$ARCH.tar.gz" >> $GITHUB_ENV
          fi
        env:
          OS: ${{ matrix.os }}
          ARCH: ${{ matrix.arch }}

      - name: Download spc
        run: gh release download --repo crazywhalecc/static-php-cli --pattern "$SPC"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Install spc
        run: |
          mkdir -p /tmp/spc
          tar -xzvf "$SPC" --directory /tmp/spc
          echo "/tmp/spc" >> "$GITHUB_PATH"

      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            craft.yml
          sparse-checkout-cone-mode: false
      - uses: actions/download-artifact@v5
        with:
          name: composer-semver.phar
          path: phar

      - run: mkdir -p out
      - run: spc craft
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: spc micro:combine ./phar/composer-semver --output out/composer-semver

      - run: tar -czvf "composer-semver-$NAME.tar.gz" -C out composer-semver
        env:
          NAME: ${{ matrix.name }}
      - uses: actions/upload-artifact@v4
        with:
          name: "composer-semver-${{ matrix.os }}-${{ matrix.arch }}.tar.gz"
          path: "composer-semver-${{ matrix.os }}-${{ matrix.arch }}.tar.gz"
          if-no-files-found: error
