name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Git tag for the release. For example, v1.2.3'
        required: true
      run_id:
        description: 'ID of the CI workflow run that created the release assets'
        type: number
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ inputs.version }}
  cancel-in-progress: true

permissions: {}

jobs:
  drafter:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          version: ${{ inputs.version }}
          tag: ${{ inputs.version }}
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deb:
    needs: drafter
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: write
      actions: read
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: deb
          path: deb
          run-id: ${{ inputs.run_id }}
          github-token: ${{ github.token }}

      - run: ls -R . # TODO!

      - uses: actions/attest-build-provenance@v3
        with:
          subject-path: deb/*.deb

      - name: Upload debs
        run: |
          while IFS= read -u3 -r -d '' deb; do 
            echo "::group::==> ${deb}"
            gh release upload --clobber --repo "${REPO}" "${TAG}" "${deb}"
            echo "::endgroup::"
          done 3< <(find deb -type f -name '*.deb' -print0)
        env:
          REPO: ${{ github.repository }}
          TAG: ${{ inputs.version }}
          GH_TOKEN: ${{ github.token }}

  tarball:
    needs: drafter
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            README.md
            LICENSE
          sparse-checkout-cone-mode: false
          ref: ${{ inputs.version }}

      - uses: actions/download-artifact@v5
        with:
          pattern: composer-semver_*_*
          path: bin
          run-id: ${{ inputs.run_id }}
          github-token: ${{ github.token }}

      - name: Find binaries
        run: |
          echo 'BIN_DIRS<<EOF' >> "$GITHUB_ENV"
          while IFS= read -u3 -r -d '' full_bin_path; do
            echo "::group::==> ${full_bin_path}"
            full_dir=$(dirname "${full_bin_path}")
            dir=$(basename -a "${full_dir}")
            echo "${dir}" >> "$GITHUB_ENV"
            echo "::endgroup::"
          done 3< <(find bin -maxdepth 2 -mindepth 2 -type f -name 'composer-semver' -print0)
          echo EOF >> "$GITHUB_ENV"
      - run: echo "${BIN_DIRS}"

      - run: mkdir -p tarball

      - name: Create tarballs
        run: |
          while read -u3 -r -d ':' bin_dir; do
            echo "::group::==> ${bin_dir}"
            cp README.md LICENSE "bin/${bin_dir}/"
            chmod +x "bin/${bin_dir}/composer-semver" && \
            tar -C "bin/${bin_dir}" -cvf - composer-semver README.md LICENSE | \
            gzip --best - > "tarball/${bin_dir}.tar.gz"
            echo "::endgroup::"
          done 3< <(echo "${BIN_DIRS}")

      # TODO!
      - run: echo "aaa" >> tarball/composer-semver_Linux_amd64.tar.gz

      - name: Validate tarballs
        run: |
          while read -u3 -r -d ':' bin_dir; do
            echo "::group::==> ${bin_dir}"
            tar -ztf "tarball/${bin_dir}.tar.gz"
            echo "::endgroup::"
          done 3< <(echo "${BIN_DIRS}")

      - uses: actions/attest-build-provenance@v3
        with:
          subject-path: tarball/*.tar.gz

      - name: Upload tarballs
        run: |
          while read -u3 -r -d ':' bin_dir; do
            echo "::group::==> ${bin_dir}"
            gh release upload --clobber --repo "${REPO}" "${TAG}" "tarball/${bin_dir}.tar.gz"
            echo "::endgroup::"
          done 3< <(echo "${BIN_DIRS}")
        env:
          REPO: ${{ github.repository }}
          TAG: ${{ inputs.version }}
          GH_TOKEN: ${{ github.token }}
