name: Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: {}

env:
  GOFLAGS: '-mod=mod'

jobs:
  phar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
          tools: box:4

      - uses: ramsey/composer-install@v3
        with:
          composer-options: --no-dev --prefer-dist

      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Print composer-semver binary path
        run: go test -count=1 -v ./internal

      - run: go test -count=1 ./...
